image: "python:3.6-stretch"

variables:
  GIT_STRATEGY: "fetch"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PIPENV_VENV_IN_PROJECT: "true"

cache:
  paths:
    - ".cache/pip"
    - ".venv/"

before_script:
  - "pip install pipenv"

run_black:
  script:
    - "pipenv sync --dev"
    - "pipenv run black ."

typecheck:
  script:
    - "pipenv sync --dev"
    - "pipenv run mypy black.py blackd.py tests/test_black.py"

unit_tests:
  script:
    - "pipenv sync --dev"
    - "pipenv run coverage run tests/test_black.py"
